name: pokebox
description: "A Flutter app that lets you explore Pok√©mon data through the PokeAPI. Search, view stats, abilities, and types with a clean, responsive UI"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  dio: ^5.9.0
  get_it: ^9.0.5
  skeletonizer: ^2.1.0+1
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0





flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


